import os

tag_map = {
    "Abdurrahman Wahid.md": ["spirituality", "public-intellectual"],
    "Bertrand Russell.md": ["philosophy", "classic-thinker"],
    "Fahruddin Faiz.md": ["spirituality", "modern-thinker"],
    "Ibnu Rusyd.md": ["philosophy", "spirituality", "classic-thinker"],
    "Mohammad Hatta.md": ["public-intellectual", "economics"],
    "Richard Dawkins.md": ["science", "public-intellectual"],
    "Abu Takeru.md": ["modern-thinker"],
    "Bill Gates.md": ["technology", "economics"],
    "Figure.md": ["misc"],
    "Immanuel Kant.md": ["philosophy", "classic-thinker"],
    "Muhammad Iqbal.md": ["spirituality", "philosophy"],
    "Richard Rorty.md": ["philosophy", "modern-thinker"],
    "Ainun Najib.md": ["technology", "public-intellectual"],
    "Blaise Pascal.md": ["philosophy", "science", "classic-thinker"],
    "Friedrich Nietzsche.md": ["philosophy", "classic-thinker"],
    "Ismail Fahmi.md": ["technology", "modern-thinker"],
    "Muhammad.md": ["spirituality"],
    "Romanticism.md": ["literature", "philosophy"],
    "Alain de Botton.md": ["philosophy", "modern-thinker"],
    "Bo Burnham.md": ["literature", "modern-thinker"],
    "Fyodor Dostoevsky.md": ["literature", "philosophy"],
    "Jacques Lacan.md": ["philosophy", "modern-thinker"],
    "Mulla Sadra.md": ["spirituality", "philosophy"],
    "Sam Altman.md": ["technology", "economics"],
    "Aldous Huxley.md": ["literature", "philosophy"],
    "Carl Sagan.md": ["science", "public-intellectual"],
    "Gabor Maté.md": ["public-intellectual", "modern-thinker"],
    "Jean-Jacques Rousseau.md": ["philosophy", "classic-thinker"],
    "Nassim Nicholas Taleb.md": ["economics", "philosophy"],
    "Alexandra Elbakyan.md": ["technology", "science"],
    "Charles Darwin.md": ["science", "classic-thinker"],
    "Gavin Wood.md": ["technology", "modern-thinker"],
    "Jean-Paul Sartre.md": ["philosophy", "literature"],
    "Naval Ravikant.md": ["economics", "modern-thinker"],
    "Sigmund Freud.md": ["philosophy", "science"],
    "Al-Farabi.md": ["philosophy", "spirituality"],
    "Charles Hoskinson.md": ["technology"],
    "George Orwell.md": ["literature", "public-intellectual"],
    "Jeff Bezos.md": ["economics", "technology"],
    "Slavoj Žižek.md": ["philosophy", "modern-thinker"],
    "Andrej Karpathy.md": ["technology", "modern-thinker"],
    "Corey Schafer.md": ["technology"],
    "Georg Wilhelm Friedrich Hegel.md": ["philosophy", "classic-thinker"],
    "Karen Armstrong.md": ["spirituality", "public-intellectual"],
    "Noam Chomsky.md": ["philosophy", "public-intellectual"],
    "Suhrawardi.md": ["spirituality", "philosophy"],
    "Andrew Huberman.md": ["science", "modern-thinker"],
    "Dan Koe.md": ["modern-thinker"],
    "Goenawan Mohamad.md": ["literature", "public-intellectual"],
    "Karl Marx.md": ["philosophy", "economics"],
    "Paulo Coelho.md": ["literature", "spirituality"],
    "Tere Liye.md": ["literature"],
    "Aristotle.md": ["philosophy", "classic-thinker"],
    "David Deutsch.md": ["science", "philosophy"],
    "Haruki Murakami.md": ["literature"],
    "Khalid Basalamah.md": ["spirituality"],
    "Peter Thiel.md": ["technology", "economics"],
    "Viktor Frankl.md": ["psychology", "philosophy"],
    "Arthur Schopenhauer.md": ["philosophy", "classic-thinker"],
    "Dimitri Bianco.md": ["economics", "modern-thinker"],
    "Ibn Arabi.md": ["spirituality", "philosophy"],
    "Linus Torvalds.md": ["technology"],
    "Plato.md": ["philosophy", "classic-thinker"],
    "Vitalik Buterin.md": ["technology", "economics"],
    "Auguste Comte.md": ["philosophy", "classic-thinker"],
    "Edmund Husserl.md": ["philosophy"],
    "Ibn Bajjah.md": ["philosophy", "spirituality"],
    "Mahatma Gandhi.md": ["spirituality", "public-intellectual"],
    "Pramoedya Ananta Toer.md": ["literature", "public-intellectual"],
    "Voltaire.md": ["philosophy", "literature"],
    "Avempace.md": ["philosophy", "spirituality"],
    "Edward Snowden.md": ["technology", "public-intellectual"],
    "Ibn Khaldun.md": ["philosophy", "economics"],
    "Mark Manson.md": ["modern-thinker"],
    "Ray Dalio.md": ["economics"],
    "Warren Buffett.md": ["economics"],
    "Averröes.md": ["philosophy", "spirituality"],
    "Elon Musk.md": ["technology", "economics"],
    "Ibn Sina.md": ["philosophy", "science"],
    "Mark Zuckerberg.md": ["technology"],
    "William James.md": ["philosophy", "psychology"],
    "Ayn Rand.md": ["philosophy", "literature"],
    "Emha Ainun Nadjib.md": ["literature", "spirituality"],
    "Ibn Taymiyya.md": ["spirituality", "philosophy"],
    "Martin Heidegger.md": ["philosophy"],
    "René Descartes.md": ["philosophy", "science"],
    "René Girard.md": ["philosophy", "literature"],
    "@yacineMTB.md": ["modern-thinker"],
    "Benoit Mandelbrot.md": ["science", "mathematics"],
    "Emil Cioran.md": ["philosophy", "literature"],
    "Ibn Tufayl.md": ["philosophy", "spirituality"],
    "Michael Burry.md": ["economics"],
}

def add_tags_to_file(file_path, tags):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    if content.startswith('---'):
        return  # Already has frontmatter
    frontmatter = f"---\ntags: [{', '.join(tags)}]\n---\n\n"
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(frontmatter + content)

folder_path = "."

for filename, tags in tag_map.items():
    path = os.path.join(folder_path, filename)
    if os.path.isfile(path):
        add_tags_to_file(path, tags)
